## Basic functions in numpy 

In [1]:
#Importing numpy
import numpy as np

In [2]:
# generate zeros 
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# generate series of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
# Creating series of 5 
n = np.ones(10)
print(n*5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [6]:
#Creating array of intergers between 10 and 50
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
# Creating random numbers of integers between 10 and 50
np.random.randint(10,51,10)

array([23, 12, 18, 49, 27, 31, 18, 29, 45, 39])

## Creation of Matrix

In [8]:
#Creating Matrix from numbers between 0 and 8
m = [[0,1,2],[3,4,5],[6,7,8]]
np.array(m)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
#Creating identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# Generating random number between 0 and 1
np.random.rand(1)

array([0.29168489])

In [12]:
# Normally distributed random numbers
np.random.randn(25)

array([-0.20351267, -0.85359424, -0.94893161, -1.1816136 ,  0.93480191,
        0.53592793,  0.33201587,  0.00824587, -0.42910135, -0.37355271,
       -2.43697196, -0.02540746,  1.33768213,  0.89821377, -1.96070916,
       -1.18778488, -0.18186964, -0.76270246, -3.25031102,  0.41058387,
        0.61157678,  0.2356572 ,  0.34870443,  0.5538597 , -1.01545657])

In [14]:
# Creating a 10*10 matrix
m = np.linspace(0,1,100)
m.reshape(10,10)

array([[0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
        0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909],
       [0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
        0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919],
       [0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
        0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929],
       [0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
        0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939],
       [0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
        0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949],
       [0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
        0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ],
       [0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
        0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ],
       [0.70707071, 0.71717172, 0.7272727

In [15]:
# Creating array 
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Indexing

In [16]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
# Subsetting the matrix
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [22]:
# Selecting an item in the matrix
mat[3,4]

20

In [23]:
mat[4:,0:]

array([[21, 22, 23, 24, 25]])

In [24]:
## Sum all the values in the matrix
mat.sum()

325

In [25]:
# Computing the standard deviation of matrix
mat.std()

7.211102550927978

In [26]:
# Sum of all the columns 
sum(mat)

array([55, 60, 65, 70, 75])